version: '3.4'

services:
  orgchart:
    image: orgchart
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 3006:3006
